<a href="https://colab.research.google.com/github/heejvely/python-practice/blob/main/ml_%EC%9D%B8%EC%BD%94%EB%94%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 레이블 인코딩 (영어 - 한글 오름차순으로 숫자 할당)
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고','전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

encoder = LabelEncoder()
labels = encoder.fit_transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [2]:
# encoder에 저장되어 있는 class print
print('인코딩 클래스:', encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [3]:
# 변환된 인코딩 값 원본 값으로 디코딩
print('디코딩 원본:', encoder.inverse_transform(labels))
print('디코딩 원본:', encoder.inverse_transform([0,1,4,5,3,3,2,2]))

디코딩 원본: ['TV' '냉장고' '전자레인지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']
디코딩 원본: ['TV' '냉장고' '전자레인지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


In [5]:
# 원-핫 인코딩 -> 숫자로 먼저 바꿔 줘야함. 레이블 인코딩 후 원 핫 인코딩.
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고','전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
encoder = LabelEncoder()
labels = encoder.fit_transform(items)
labels = labels.reshape(-1, 1)

oh_encoder = OneHotEncoder()
oh_labels = oh_encoder.fit_transform(labels)
print('원-핫 인코딩:')
print(oh_labels.toarray()) # <-- 배열로 변경

원-핫 인코딩:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [8]:
import pandas as pd

items = ['TV', '냉장고','전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
item_df = pd.DataFrame(data=items, columns=['item'])
item_dummies = pd.get_dummies(item_df)
item_dummies

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0